// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6Dw3BKweqhrKkGB02Fs2X59CgM5KIlA',
    appId: '1:312865857869:web:187969e0ba15a0eb021704',
    messagingSenderId: '312865857869',
    projectId: 'stop-chat-3ab7b',
    authDomain: 'stop-chat-3ab7b.firebaseapp.com',
    storageBucket: 'stop-chat-3ab7b.firebasestorage.app',
    measurementId: 'G-QPVQ88Y56F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRdk2ozXBUtwo6b_xX6XRg6V1iGXA6amo',
    appId: '1:312865857869:android:437b55b4982a2d3e021704',
    messagingSenderId: '312865857869',
    projectId: 'stop-chat-3ab7b',
    storageBucket: 'stop-chat-3ab7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4-_3stqebuLUwuezS8wTzfAqbEkc5YU',
    appId: '1:312865857869:ios:129b62e610b4c4d8021704',
    messagingSenderId: '312865857869',
    projectId: 'stop-chat-3ab7b',
    storageBucket: 'stop-chat-3ab7b.firebasestorage.app',
    iosBundleId: 'com.example.bikespot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD4-_3stqebuLUwuezS8wTzfAqbEkc5YU',
    appId: '1:312865857869:ios:129b62e610b4c4d8021704',
    messagingSenderId: '312865857869',
    projectId: 'stop-chat-3ab7b',
    storageBucket: 'stop-chat-3ab7b.firebasestorage.app',
    iosBundleId: 'com.example.bikespot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE6Dw3BKweqhrKkGB02Fs2X59CgM5KIlA',
    appId: '1:312865857869:web:84986b013e95237c021704',
    messagingSenderId: '312865857869',
    projectId: 'stop-chat-3ab7b',
    authDomain: 'stop-chat-3ab7b.firebaseapp.com',
    storageBucket: 'stop-chat-3ab7b.firebasestorage.app',
    measurementId: 'G-2CYC1N5M1E',
  );

}